---
title: "Brechas de género en elecciones"
format:
  html: 
     fig-align: "center"
     fig-width: 9
     fig-height: 7
     self-contained: true
execute: 
  messages: false
  warning: false
  echo: false

---

Realizado en base a datos de [resultados electorales históricos de Servel](https://www.servel.cl/centro-de-datos/resultados-electorales-historicos-gw3/).

```{r setup}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
library(ggtext)
library(glue)
library(here)

source(here("funciones.R"))

concejales <- read_csv2(here("datos/resultados_servel_2024_concejales.csv")) |> ordenar_regiones()
alcaldes <- read_csv2(here("datos/resultados_servel_2024_alcaldes.csv")) |> ordenar_regiones()
cores <- read_csv2(here("datos/resultados_servel_2024_cores.csv")) |> ordenar_regiones()
```


## País
```{r pais}
#| fig-width: 9
#| fig-height: 4

concejales |> 
  group_by(genero) |> 
  summarize(n = n()) |> 
  mutate(p = n/sum(n)) |> 
  grafico_pais() +
  labs(title = "**Concejales 2024**", 
       subtitle = glue("Porcentaje de concejalías electas, **{color('mujeres', femenino)}** y **{color('hombres', masculino)}**")) +
  tema_torta


alcaldes |> 
  group_by(genero) |> 
  summarize(n = n()) |> 
  mutate(p = n/sum(n)) |> 
  grafico_pais() +
  labs(title = "**Alcaldes 2024**", 
       subtitle = glue("Porcentaje de alcaldías electas, **{color('mujeres', femenino)}** y **{color('hombres', masculino)}**")) +
  tema_torta


cores |> 
  group_by(genero) |> 
  summarize(n = n()) |> 
  mutate(p = n/sum(n)) |> 
  grafico_pais() +
  labs(title = "**Consejeros/as regionales 2024**", 
       subtitle = glue("Porcentaje de cores electos, **{color('mujeres', femenino)}** y **{color('hombres', masculino)}**")) +
  tema_torta
```



## Región
```{r region}
concejales |> 
  group_by(nombre_region, genero) |> 
  summarize(n = n()) |> 
  mutate(p = n/sum(n)) |> 
  grafico_regiones() +
  labs(title = "**Concejales/as 2024**", 
       subtitle = glue("Porcentaje de concejalías electas, **{color('hombres', masculino)}** y **{color('mujeres', femenino)}**")) +
  tema_barras_horizontales


alcaldes |> 
  group_by(nombre_region, genero) |> 
  summarize(n = n()) |> 
  mutate(p = n/sum(n)) |> 
  grafico_regiones() +
  labs(title = "**Alcaldías 2024**", 
       subtitle = glue("Porcentaje de alcaldías electas, **{color('hombres', masculino)}** y **{color('mujeres', femenino)}**")) +
  tema_barras_horizontales

cores |> 
  group_by(nombre_region, genero) |> 
  summarize(n = n()) |> 
  mutate(p = n/sum(n)) |> 
  grafico_regiones() +
  labs(title = "**Consejeros/as regionales 2024**", 
       subtitle = glue("Porcentaje de cores electos, **{color('hombres', masculino)}** y **{color('mujeres', femenino)}**")) +
  tema_barras_horizontales

```

